version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
#    ports:
#      - 1883:1883
#      - 9001:9001
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - TZ=Europe/Copenhagen
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2
    container_name: zigbee2mqtt
    restart: unless-stopped
#    ports:
#      - 8080:8080
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0 # This is the USB device that Conbee II is running on.
    environment:
      - TZ=Europe/Copenhagen
    depends_on:
      - mosquitto
  node-red:
    image: nodered/node-red:4.0
    container_name: node-red
    restart: unless-stopped
#    ports:
#      - 1880:1880
    volumes: 
      - ./node-red/data:/data
    environment:
      - TZ=Europe/Copenhagen
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Europe/Copenhagen
    depends_on:
      - node-red
      - zigbee2mqtt
